### ISSUE TITLE
A problem with shuffle product

### ISSUE THREAD

**Issue by terrylyons** [terrylyons/libalgebra#45]
`
	TEST_FIXTURE(Fixture, basic_shuffles) {
		auto show_container = [](auto& arg) {std::cout << "|"; for (auto k : arg) std::cout << k << "|"; return arg; };
		const SHUFFLE_TENSOR szero;
		const SKEY sunit;
		const SHUFFLE_TENSOR sone(S(1));
		const SHUFFLE_TENSOR l1(alg::LET(1), S(1));
		const SHUFFLE_TENSOR l2(alg::LET(2), S(1));
		const SHUFFLE_TENSOR l3(alg::LET(3), S(1));
		std::cout << l1*l2 << std::endl;
`
Does not currently compile.  the failure is in tensor.h at line 472; it looks to me as if key_t is not defined. The above code compiles and runs as expected if l1*l2 is replaced by l1
[Compiler output.txt](https://github.com/terrylyons/libalgebra/files/7449595/Compiler.output.txt)

Looking further;  the class shuffle_tensor_multiplication has a templated function _prod which defines key_t on the first line (line 451 of the file) and this definition had been commented out. key_t is an essential definition used many times in _prod. I have uncommented the definition and everything seems to compile. Have I introduced problems elsewhere?
.

**Comment by inakleinbottle** [comment]
Ok this one has me stumped I don't know why this value would have been commented out, clearly it should not be! I will investigate and make a fix pull request shortly.

**Comment by inakleinbottle** [comment]
I've reviewed the code. This comment was introduce as part of a job to cut down compiler warnings before shuffle tensor had tests. This line has been uncommented in when shuffle tensor tests were merged. So updating libalgebra to the most recent version of develop should fix the problem.

**Comment by inakleinbottle** [comment]
I think this problem has been resolved, so I'm going to close this issue.
